/**
 * Crafted in Erebor by thorin on 2019-02-11
 */
export const COLLECTIONS_FETCH = 'COLLECTIONS_FETCH';
export const COLLECTIONS_FETCH_SUCCESS = 'COLLECTIONS_FETCH_SUCCESS';
export const COLLECTIONS_FETCH_FAILED = 'COLLECTIONS_FETCH_FAILED';
